### ISSUE TITLE
Datepicker is marked "ng-dirty" even when no changes are made to its value

### ISSUE THREAD

**Issue by ubous** [rpussente/frte-ng-datepicker#1]
I have a form in my application that checks if there are any fields dirty and notifies the user when he leaves before saving it.

I noticed that the notification popped up even when no changes are made on the form.
Then I found out that frte-datepicker is getting marked "ng-dirty" by angular.

**Comment by waldirpereira** [comment]
@rpussente Now you can close this issue and then release a new version. Thks!
